language: objective-c
osx_image: xcode7.3
script:
- xctool test -project FontWeather.xcodeproj -scheme FontWeather -sdk iphonesimulator
  ONLY_ACTIVE_ARCH=NO
- xctool -project FontWeather.xcodeproj -scheme FontWeather-watchOS -sdk watchsimulator
  ONLY_ACTIVE_ARCH=NO
before_deploy:
  - carthage build --no-skip-current
  - carthage archive FontWeather
